### PR TITLE
Fix YouTube 5 Sec reload & Netflix loading bug

### PR DESCRIPTION
**Pull request by OrdenKrieger**
Fix YouTube 5 Sec reload & Netflix loading bug

### CODE REVIEW

**Comment by OrdenKrieger** [comment]
Her we go.

**Comment by fire855** [comment]
Thanks :)

**Comment by degrus** [comment]
too late fix released till yesterday

**Comment by fire855** [comment]
Then you are very late.
Ordenkrieger released his fix 25 days ago. https://github.com/fire855/android_vendor_kingzone_k1-turbo/pull/2

**Pull request merged**
